from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

from app.models.task import TaskPriority, TaskStatus
from app.schemas.report import ReportResponse
from app.schemas.task import TaskResponse


# ── Inbound payloads (client → server) ───────────────────────────────────────

class SyncTaskPayload(BaseModel):
    """
    A task record as the mobile client knows it.

    `client_updated_at` is the device-local timestamp of the last modification.
    The server uses this (along with `client_version`) to apply the chosen
    conflict resolution strategy.
    """

    client_id: uuid.UUID
    title: str = Field(min_length=1, max_length=255)
    description: str | None = None
    status: TaskStatus = TaskStatus.PENDING
    priority: TaskPriority = TaskPriority.MEDIUM
    assigned_to_id: uuid.UUID | None = None
    location_lat: float | None = None
    location_lng: float | None = None
    location_address: str | None = None
    scheduled_at: datetime | None = None
    started_at: datetime | None = None
    completed_at: datetime | None = None
    # Metadata the server uses for conflict resolution:
    client_updated_at: datetime
    client_version: int = Field(ge=0, description="0 for new records never synced before.")


class SyncReportPayload(BaseModel):
    """
    The `task_client_id` references the task by the device's local UUID rather
    than the server-assigned `id`.  This is necessary when a new task and its
    report are both created offline — the client doesn't know the server `id`
    for the task yet.  The sync engine resolves `task_client_id → task.id`
    before persisting.
    """

    client_id: uuid.UUID
    task_client_id: uuid.UUID = Field(
        description="Client-side UUID of the parent task."
    )
    content: str = Field(min_length=1)
    materials_used: list[dict[str, Any]] | None = None
    time_spent_minutes: int | None = Field(default=None, ge=0)
    client_updated_at: datetime
    client_version: int = Field(ge=0)


class SyncPhotoPayload(BaseModel):
    """
    Photo metadata only — binary upload happens via a separate multipart
    endpoint POST /photos/upload.  The sync engine records the metadata and
    marks the photo as pending upload if the server hasn't received the binary.
    """

    client_id: uuid.UUID
    task_client_id: uuid.UUID
    report_client_id: uuid.UUID | None = None
    original_filename: str = Field(max_length=255)
    mime_type: str = Field(max_length=64)
    file_size_bytes: int = Field(gt=0)
    sha256_checksum: str = Field(min_length=64, max_length=64)
    client_created_at: datetime


class SyncRequest(BaseModel):
    device_id: str = Field(
        min_length=1,
        max_length=128,
        description="Stable per-installation identifier generated by the mobile app.",
    )
    last_synced_at: datetime | None = Field(
        default=None,
        description="The server_timestamp from the previous SyncResponse. "
                    "Null on first sync — the server returns everything.",
    )
    tasks: list[SyncTaskPayload] = Field(default_factory=list)
    reports: list[SyncReportPayload] = Field(default_factory=list)
    photos: list[SyncPhotoPayload] = Field(default_factory=list)


# ── Outbound payloads (server → client) ──────────────────────────────────────

class PhotoMetaResponse(BaseModel):
    id: uuid.UUID
    client_id: uuid.UUID
    task_id: uuid.UUID
    report_id: uuid.UUID | None
    original_filename: str
    file_path: str
    mime_type: str
    file_size_bytes: int
    sha256_checksum: str
    client_created_at: datetime
    created_at: datetime

    class Config:
        from_attributes = True


class ConflictDetail(BaseModel):
    """
    Describes a record where the client's version was rejected.

    The client should replace its local copy with `server_state`.
    """

    entity_type: Literal["task", "report"]
    client_id: uuid.UUID
    server_id: uuid.UUID
    resolution: Literal["server_wins", "client_wins", "latest_timestamp_server", "latest_timestamp_client"]
    client_updated_at: datetime
    server_updated_at: datetime
    server_version: int


class SyncResponse(BaseModel):
    """
    The authoritative server state the client should merge into its local DB.

    `server_timestamp` becomes the client's next `last_synced_at` watermark.
    """

    server_timestamp: datetime
    tasks: list[TaskResponse]
    reports: list[ReportResponse]
    photos: list[PhotoMetaResponse]
    conflicts: list[ConflictDetail]
    stats: "SyncStats"


class SyncStats(BaseModel):
    tasks_received: int
    tasks_sent: int
    reports_received: int
    reports_sent: int
    photos_received: int
    photos_sent: int
    conflicts_detected: int


SyncResponse.model_rebuild()
